# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  name: CoreBuild-Pool

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/SuiteSparse

parameters:
- name: NugetVersion
  type: string
  default: 5.x

# Access yaml templates from Shared repo
resources:
  repositories:
    - repository: Templates
      type: git
      name: CB.Pipelines

  
variables:
  projectSourcePath: 'src/SuiteSparse'
  
name: $(BuildDefinitionName)_$(Date:yyyy).$(Date:MM).$(Date:dd).$(Rev:.rrr)

stages:
- stage: BuildAndVerify
  displayName: Build and Verify
  jobs:
  - template: SharedTemplates/Multi-Configuration-Job.yml@Templates
    parameters:
      JobName: Build
      DisplayName: Build
      BuildConfiguration:
      - release
      BuildSteps:
      - task: NuGetToolInstaller@1
        displayName: 'Use NuGet ${{ parameters.NugetVersion }}'
        inputs:
          versionSpec:  ${{ parameters.NugetVersion }}

      - task: NuGetAuthenticate@0

      - task: NuGetCommand@2
        displayName: 'NuGet restore'
        inputs:
          command: restore
          restoreSolution: $(projectSourcePath)/SuiteSparse.sln
          feedsToUse: config
          nugetConfigPath: $(projectSourcePath)/NuGet.Config   
      - task: VSBuild@1
        displayName: 'Build BuildTools.sln'
        inputs:
          solution: $(projectSourcePath)/*.sln
          msbuildArgs: '/fl /flp:LogFile=$(Build.SourcesDirectory)\Logs\MsBuild.log;Verbosity=diagnostic'
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'
          clean: true
          maximumCpuCount: true
          createLogFile: true
      - publish: '$(Build.SourcesDirectory)\$(projectSourcePath)\SuiteSparse_UT\SuiteSparseBin'
        artifact: 'SuiteSparse_$(BuildPlatform)_$(BuildConfiguration)'

- stage: ProduceNuget
  jobs:
  - job: SuiteSparse_Vcpkg_to_nuGet
    displayName: SuiteSparse Vcpkg to nuGet
    pool: CoreBuild-Pool-Lite
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'current'
        path: $(projectSourcePath)\artifacts
        artifact: SuiteSparse_x86_release
        
    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'current'
        path: $(projectSourcePath)\artifacts
        artifact: SuiteSparse_x64_release

    - task: NuGetCommand@2
      displayName: NuGet pack
      inputs:
        command: pack
        searchPatternPack: '$(projectSourcePath)/**/*.nuspec'
        configurationToPack: ''
        outputDir: $(Build.BinariesDirectory)
        versioningScheme: byBuildNumber
        basePath: $(projectSourcePath)

    - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      - task: NuGetCommand@2
        displayName: 'NuGet push'
        inputs:
          command: push
          packagesToPush: '$(Build.BinariesDirectory)\**\*.nupkg'
          publishVstsFeed: '23c8a906-5e52-4f73-8e75-c44ee826f3bf'